name: Dev-Deploy

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    env:
      SSH_KEY: ${{secrets.SSH_KEY}}
      VITE_SEARCHKIT_ENDPOINT: ${{secrets.VITE_SEARCHKIT_ENDPOINT}}
      VITE_SEARCHKIT_API_KEY: ${{secrets.VITE_SEARCHKIT_API_KEY}}
      VITE_SEARCHKIT_ENTITIES_INDEX: ${{secrets.VITE_SEARCHKIT_ENTITIES_INDEX}}
      VITE_SEARCHKIT_LETTERS_INDEX: ${{secrets.VITE_SEARCHKIT_LETTERS_INDEX}}
      REMOTE_DEV_HOST: ${{secrets.REMOTE_DEV_HOST}}
      REMOTE_USER: ${{secrets.REMOTE_USER}}


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - run: npm run build
    - run: mkdir ~/.ssh
    - run: 'echo "$SSH_KEY" >> ~/.ssh/id_rsa'
    - run: chmod 400 ~/.ssh/id_rsa
    - run: 'rsync -e "ssh -o StrictHostKeyChecking=no" dist/* $REMOTE_USER@$REMOTE_DEV_HOST:~/$REMOTE_DEV_HOST/'
